from __future__ import annotations

from importlib.util import find_spec
from pathlib import Path

from pptx import Presentation
from pptx.dml.color import RGBColor
from pptx.enum.shapes import MSO_SHAPE
from pptx.enum.text import PP_ALIGN, MSO_ANCHOR
from pptx.util import Inches, Pt

from reins.features.presentation.engines.base import (
    EngineHealth,
    PresentationEngineAdapter,
)
from reins.features.presentation.engines.visuals import (
    PresentationPalette,
    get_palette,
    slugify,
)
from reins.features.presentation.models import (
    PresentationArtifact,
    PresentationEngine,
    PresentationOutputFormat,
    PresentationPlan,
    PresentationRequest,
    PresentationResult,
    PresentationSlide,
)


class NativePptxEngine(PresentationEngineAdapter):
    name = PresentationEngine.NATIVE_PPTX

    def health(self) -> EngineHealth:
        python_pptx_available = find_spec("pptx") is not None

        if not python_pptx_available:
            return EngineHealth(
                name=self.name,
                available=False,
                message=(
                    "python-pptx is not installed in the active "
                    "Reins environment."
                ),
            )

        return EngineHealth(
            name=self.name,
            available=True,
            message="Native python-pptx engine is available.",
        )

    def render(
        self,
        *,
        request: PresentationRequest,
        plan: PresentationPlan,
        workspace: Path,
    ) -> PresentationResult:
        if request.output_format != PresentationOutputFormat.PPTX:
            raise ValueError("native_pptx only supports PPTX output.")

        output_dir = workspace / "output"
        output_dir.mkdir(parents=True, exist_ok=True)
        output_path = output_dir / f"{slugify(plan.title)}.pptx"
        presentation = Presentation()

        if plan.aspect_ratio == "4:3":
            presentation.slide_width = Inches(10)
            presentation.slide_height = Inches(7.5)
        else:
            presentation.slide_width = Inches(13.333333)
            presentation.slide_height = Inches(7.5)

        palette = get_palette(plan.style)
        blank_layout = presentation.slide_layouts[6]

        for slide_plan in plan.slides:
            slide = presentation.slides.add_slide(blank_layout)
            _render_slide(
                presentation,
                slide,
                plan=plan,
                slide_plan=slide_plan,
                palette=palette,
            )

            if slide_plan.speaker_notes:
                try:
                    slide.notes_slide.notes_text_frame.text = (
                        slide_plan.speaker_notes
                    )
                except (AttributeError, ValueError):
                    pass

        presentation.core_properties.title = plan.title
        presentation.core_properties.subject = (
            plan.audience or "Presentation generated by Reins Agent"
        )
        presentation.core_properties.author = "Reins Agent"
        presentation.save(output_path)

        return PresentationResult(
            success=True,
            action=request.action,
            engine=self.name,
            primary_output=output_path,
            artifacts=[
                PresentationArtifact(
                    kind="presentation",
                    path=output_path,
                    mime_type=(
                        "application/vnd.openxmlformats-officedocument."
                        "presentationml.presentation"
                    ),
                    metadata={
                        "slide_count": len(plan.slides),
                        "editable": True,
                    },
                )
            ],
        )


def _rgb(value: str) -> RGBColor:
    return RGBColor.from_string(value)


def _set_slide_background(slide, color: str) -> None:
    fill = slide.background.fill
    fill.solid()
    fill.fore_color.rgb = _rgb(color)


def _add_text(
    slide,
    text: str,
    *,
    left: float,
    top: float,
    width: float,
    height: float,
    font_size: float,
    color: str,
    bold: bool = False,
    align=PP_ALIGN.LEFT,
    margin: float = 0,
):
    box = slide.shapes.add_textbox(
        Inches(left),
        Inches(top),
        Inches(width),
        Inches(height),
    )
    frame = box.text_frame
    frame.clear()
    frame.word_wrap = True
    frame.margin_left = Inches(margin)
    frame.margin_right = Inches(margin)
    frame.margin_top = Inches(margin)
    frame.margin_bottom = Inches(margin)
    frame.vertical_anchor = MSO_ANCHOR.MIDDLE
    paragraph = frame.paragraphs[0]
    paragraph.text = text
    paragraph.alignment = align
    paragraph.font.name = "Aptos"
    paragraph.font.size = Pt(font_size)
    paragraph.font.bold = bold
    paragraph.font.color.rgb = _rgb(color)
    return box


def _add_rect(
    slide,
    *,
    left: float,
    top: float,
    width: float,
    height: float,
    fill: str,
    line: str | None = None,
    radius: bool = False,
):
    shape_type = MSO_SHAPE.ROUNDED_RECTANGLE if radius else MSO_SHAPE.RECTANGLE
    shape = slide.shapes.add_shape(
        shape_type,
        Inches(left),
        Inches(top),
        Inches(width),
        Inches(height),
    )
    shape.fill.solid()
    shape.fill.fore_color.rgb = _rgb(fill)
    if line:
        shape.line.color.rgb = _rgb(line)
        shape.line.width = Pt(1)
    else:
        shape.line.fill.background()
    return shape


def _slide_items(slide_plan: PresentationSlide) -> list[str]:
    items: list[str] = []
    for element in slide_plan.elements:
        if element.text:
            items.append(element.text)
        items.extend(element.items)
    return [" ".join(item.split()) for item in items if item.strip()][:6]


def _render_slide(
    presentation: Presentation,
    slide,
    *,
    plan: PresentationPlan,
    slide_plan: PresentationSlide,
    palette: PresentationPalette,
) -> None:
    _set_slide_background(slide, palette.background)
    slide_width = presentation.slide_width / Inches(1)
    slide_height = presentation.slide_height / Inches(1)
    _add_rect(
        slide,
        left=0,
        top=0,
        width=0.15,
        height=slide_height,
        fill=palette.accent,
    )

    if slide_plan.index == 1 or slide_plan.type == "title":
        _render_title_slide(
            slide,
            slide_width=slide_width,
            slide_height=slide_height,
            plan=plan,
            slide_plan=slide_plan,
            palette=palette,
        )
        return

    _add_text(
        slide,
        f"SECTION {slide_plan.index:02d}",
        left=0.65,
        top=0.35,
        width=3.4,
        height=0.35,
        font_size=10,
        color=palette.accent,
        bold=True,
    )
    title_size = 25 if len(slide_plan.title) < 48 else 21
    _add_text(
        slide,
        slide_plan.title,
        left=0.65,
        top=0.75,
        width=slide_width - 1.3,
        height=0.85,
        font_size=title_size,
        color=palette.text,
        bold=True,
    )

    items = _slide_items(slide_plan) or [slide_plan.subtitle or slide_plan.title]
    if slide_plan.index % 2 == 0 or len(items) >= 5:
        _render_cards(
            slide,
            slide_width=slide_width,
            items=items,
            palette=palette,
        )
    else:
        _render_list(
            slide,
            slide_width=slide_width,
            items=items,
            palette=palette,
        )

    _add_text(
        slide,
        plan.title[:64],
        left=0.65,
        top=slide_height - 0.42,
        width=slide_width - 2.2,
        height=0.22,
        font_size=8,
        color=palette.muted,
        bold=True,
    )
    _add_text(
        slide,
        f"{slide_plan.index:02d} / {len(plan.slides):02d}",
        left=slide_width - 1.35,
        top=slide_height - 0.42,
        width=0.75,
        height=0.22,
        font_size=8,
        color=palette.muted,
        bold=True,
        align=PP_ALIGN.RIGHT,
    )


def _render_title_slide(
    slide,
    *,
    slide_width: float,
    slide_height: float,
    plan: PresentationPlan,
    slide_plan: PresentationSlide,
    palette: PresentationPalette,
) -> None:
    _add_text(
        slide,
        "REINS PRESENTATION",
        left=0.8,
        top=0.65,
        width=4.0,
        height=0.4,
        font_size=11,
        color=palette.accent,
        bold=True,
    )
    title_size = 37 if len(slide_plan.title) < 48 else 30
    _add_text(
        slide,
        slide_plan.title,
        left=0.8,
        top=1.35,
        width=slide_width - 4.45,
        height=2.6,
        font_size=title_size,
        color=palette.text,
        bold=True,
    )
    subtitle = slide_plan.subtitle or plan.subtitle or plan.audience
    if subtitle:
        _add_text(
            slide,
            subtitle,
            left=0.82,
            top=4.35,
            width=slide_width - 4.6,
            height=0.72,
            font_size=16,
            color=palette.muted,
        )
    _add_rect(
        slide,
        left=0.82,
        top=5.55,
        width=2.0,
        height=0.09,
        fill=palette.primary,
    )
    _add_rect(
        slide,
        left=2.92,
        top=5.55,
        width=0.72,
        height=0.09,
        fill=palette.secondary,
    )
    panel_left = slide_width - 3.35
    _add_rect(
        slide,
        left=panel_left,
        top=0.75,
        width=2.7,
        height=5.35,
        fill=palette.surface,
        line=palette.primary,
        radius=True,
    )
    _add_text(
        slide,
        str(len(plan.slides)),
        left=panel_left + 0.35,
        top=1.6,
        width=1.8,
        height=1.15,
        font_size=54,
        color=palette.text,
        bold=True,
    )
    _add_text(
        slide,
        "SLIDES",
        left=panel_left + 0.38,
        top=2.7,
        width=1.4,
        height=0.35,
        font_size=10,
        color=palette.muted,
        bold=True,
    )
    _add_text(
        slide,
        plan.style.value.upper(),
        left=panel_left + 0.38,
        top=4.2,
        width=1.9,
        height=0.38,
        font_size=12,
        color=palette.accent,
        bold=True,
    )
    _add_text(
        slide,
        plan.aspect_ratio,
        left=panel_left + 0.38,
        top=4.65,
        width=1.9,
        height=0.38,
        font_size=12,
        color=palette.text,
        bold=True,
    )
    _add_text(
        slide,
        plan.title[:64],
        left=0.82,
        top=slide_height - 0.42,
        width=slide_width - 2,
        height=0.22,
        font_size=8,
        color=palette.muted,
        bold=True,
    )


def _render_cards(
    slide,
    *,
    slide_width: float,
    items: list[str],
    palette: PresentationPalette,
) -> None:
    count = min(len(items), 6)
    columns = 3 if count >= 3 else max(count, 1)
    rows = 2 if count > 3 else 1
    gap = 0.18
    available = slide_width - 1.3
    card_width = (available - gap * (columns - 1)) / columns
    card_height = 2.02 if rows == 2 else 3.45
    start_y = 1.92 if rows == 2 else 2.2

    for index, item in enumerate(items[:6]):
        column = index % columns
        row = index // columns
        left = 0.65 + column * (card_width + gap)
        top = start_y + row * (card_height + gap)
        accent = [palette.primary, palette.secondary, palette.accent][index % 3]
        _add_rect(
            slide,
            left=left,
            top=top,
            width=card_width,
            height=card_height,
            fill=palette.surface,
            line=accent,
            radius=True,
        )
        _add_rect(
            slide,
            left=left,
            top=top,
            width=card_width,
            height=0.08,
            fill=accent,
        )
        _add_text(
            slide,
            f"{index + 1:02d}",
            left=left + 0.18,
            top=top + 0.2,
            width=0.6,
            height=0.35,
            font_size=14,
            color=accent,
            bold=True,
        )
        _add_text(
            slide,
            item,
            left=left + 0.18,
            top=top + 0.7,
            width=card_width - 0.36,
            height=card_height - 0.88,
            font_size=13 if rows == 1 else 11.5,
            color=palette.text,
            bold=True,
        )


def _render_list(
    slide,
    *,
    slide_width: float,
    items: list[str],
    palette: PresentationPalette,
) -> None:
    row_height = min(0.92, 4.5 / max(len(items), 1))
    start_y = 2.0

    for index, item in enumerate(items[:5]):
        top = start_y + index * row_height
        accent = [palette.primary, palette.secondary, palette.accent][index % 3]
        _add_rect(
            slide,
            left=0.65,
            top=top,
            width=0.7,
            height=0.54,
            fill=accent,
            radius=True,
        )
        _add_text(
            slide,
            f"{index + 1:02d}",
            left=0.68,
            top=top,
            width=0.64,
            height=0.54,
            font_size=12,
            color=palette.background,
            bold=True,
            align=PP_ALIGN.CENTER,
        )
        _add_text(
            slide,
            item,
            left=1.58,
            top=top - 0.02,
            width=slide_width - 2.25,
            height=0.58,
            font_size=15,
            color=palette.text,
            bold=True,
        )
