from __future__ import annotations

from datetime import datetime
import importlib.util
from pathlib import Path
import shutil

from reins.api.home import get_reins_home


class ArtifactDependencyError(RuntimeError):
    pass


def check_artifact_dependencies() -> dict[str, bool]:
    playwright_browser = False

    if importlib.util.find_spec("playwright") is not None:
        try:
            from playwright.sync_api import sync_playwright

            with sync_playwright() as p:
                playwright_browser = Path(p.chromium.executable_path).exists()
        except Exception:
            playwright_browser = False

    return {
        "python-docx": importlib.util.find_spec("docx") is not None,
        "playwright": importlib.util.find_spec("playwright") is not None,
        "playwright-chromium": playwright_browser,
        "pillow": importlib.util.find_spec("PIL") is not None,
        "pytesseract": importlib.util.find_spec("pytesseract") is not None,
        "tesseract": shutil.which("tesseract") is not None,
    }


def _load_document_class():
    try:
        from docx import Document
    except ImportError as exc:
        raise ArtifactDependencyError(
            "Missing dependency: python-docx. Install Reins with project dependencies "
            "before running Office workmode tasks."
        ) from exc

    return Document


def get_artifact_dir() -> Path:
    path = get_reins_home() / "workmode" / "artifacts"
    path.mkdir(parents=True, exist_ok=True)
    return path


def generate_demo_docx(title: str, body: str) -> Path:
    path = get_artifact_dir() / f"report-{datetime.now().strftime('%Y%m%d-%H%M%S')}.docx"
    Document = _load_document_class()

    doc = Document()
    doc.add_heading(title, level=1)
    doc.add_paragraph(body)
    doc.add_paragraph("Generated by Reins WorkMode.")
    doc.save(path)

    return path
