from __future__ import annotations

from datetime import datetime
from pathlib import Path

from docx import Document

from reins.api.home import get_reins_home


def get_artifact_dir() -> Path:
    path = get_reins_home() / "workmode" / "artifacts"
    path.mkdir(parents=True, exist_ok=True)
    return path


def generate_demo_docx(title: str, body: str) -> Path:
    path = get_artifact_dir() / f"report-{datetime.now().strftime('%Y%m%d-%H%M%S')}.docx"

    doc = Document()
    doc.add_heading(title, level=1)
    doc.add_paragraph(body)
    doc.add_paragraph("Generated by Reins WorkMode.")
    doc.save(path)

    return path